### ISSUE TITLE
Custom /etc/hosts file

### ISSUE THREAD

**Issue by xtuc** [moby/tool#161]
My linuxkit configuration YAML file:

```yaml
[...]
files:
  - path: /etc/hosts
    contents: |
      10.0.0.0       foo
```
I expected this configuration to modify the /etc/hosts file but it seems that the `moby build` command is already providing one:

https://github.com/moby/tool/blob/cc823286f4d06df94597073cc47287d20e4898f6/src/moby/image.go#L43-L49

and It can't be modified.

Is there any reason behind this? Or could we remove it?
For my use case it would suffice to just being able to appending new lines to the file.
