### ISSUE TITLE
Proposal: builder: add `include`

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/tool#4]
I suggest adding `include` syntax (as Golang text/template function)

## Example usecase

before (https://github.com/linuxkit/linuxkit/blob/master/examples/sshd.yml):

```yaml
files:
  - path: root/.ssh/authorized_keys
    contents: '#your ssh key here'
```

after:

```yaml
files:
  - path: root/.ssh/authorized_keys
    contents: {{include ~/.ssh/id_rsa.pub}}
```

## Path resolution

- Absolute path (including one starts with `~/`): resolved to the file specified by the absolute path. Maybe woth adding `moby build --disallow-include-absolute-path` for security reason
- Relative path starts with `./` (or `.\` on Windows): resolved to the file specified by the relative path
- Others (e.g. `foo.yaml.snippet`, `foo/bar.yaml.snippet`): resolved to one of the files under the following paths: `~/.moby/include`, `/usr/local/share/moby/include`...
