### ISSUE TITLE
Proposal: builder: support inheritance

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/tool#5]
Maintaining a bunch of yaml files is really mess: https://github.com/linuxkit/linuxkit/pull/1701

So I suggest supporting inheritance (see also https://learnxinyminutes.com/docs/yaml/)

## Example

```yaml
{{import ./minimal.yml minimal}}
services:
  <<: *minimal_services
  - name: additional-foobar
     image: "additional-foobar/baz:deadbeef"
     ...
```
