### ISSUE TITLE
trust key pinning

### ISSUE THREAD

**Issue by riyazdf** [moby/tool#63]
We should allow for pinning the root key for trust repos, ex: all individual official images are signed with differing root keys and all of linuxkit's repos are signed with the same root key.

This could manifest itself in the configuration as a subkey under invidivdiual `image` and `org` subsection entries in `trust`

Still determining the best format, but perhaps something like this which will let us further expand the trust section:

```
trust:
  org:
    - name: linuxkit
    rootKey: 1908a0cf4f55710138e63f65ab2a97e8fa3948e5ca3b8857a29f235a3b61ea1b
  image:
    - name: nginx
    rootKey: d2f02ea35ebffce87d31673efbff44c199b1af0be042989d4655a176e8aad40d
```
